name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore test dependencies
      run: dotnet restore unit_test_lab6.Tests/unit_test_lab6.Tests.csproj

    - name: Build test project
      run: dotnet build \
            unit_test_lab6.Tests/unit_test_lab6.Tests.csproj \
            --configuration Release \
            --no-restore

    - name: Run unit tests
      run: |
        dotnet test \
          unit_test_lab6.Tests/unit_test_lab6.Tests.csproj \
          --configuration Release \
          --no-build \
          --logger "trx;LogFileName=test_results.trx"
